version: '3.0'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fitz
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: findmypet
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
