openapi: 3.0.1
info:
  title: Find my Pet
  description: >
    This is the documentation that describes the api
    for the find my pet web application.
  version: 1.0.0
tags:
  - name: User
    description: Endpoints for sign up and sign in users.

paths:
  /user:
    post:
      tags:
        - User
      summary: Adds a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        '400':
          description: Invalid Body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /session:
    post:
      tags:
        - User
      summary: Sign in a user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequestDto'
      responses:
        '200':
          description: Session created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponseDto'
        '400':
          description: Invalid body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          maxLength: 100
        email:
          type: string
          maxLength: 60
        password_hash:
          type: string
    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
        email:
          type: string
          maxLength: 60
          description: Valid email address. Duplicated will not be allowed.
        password:
          type: string
          maxLength: 20
        confirm_password:
          type: string
          maxLength: 20
          description: Should be equal to the password
      required:
        - name
        - email
    CreateUserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
    SessionRequestDto:
      type: object
      properties:
        email:
          type: string
          maxLength: 60
        password:
          type: string
          maxLength: 20
      required:
        - email
        - password
    SessionResponseDto:
      type: object
      properties:
        token:
          type: string
        refresh_token:
          type: string
        user:
          $ref: '#/components/schemas/User'
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message
